[project]
name = "ebird-notebooks"
version = "0.0.0"
description = "Jupyter notebooks for analysing eBird checklists"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebird-api>=3.0.7",
    "jupyterlab>=4.2.5",
    "notebook>=7.2.2",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.36",
]
